definitions:
  entities.AdminChangePWD:
    properties:
      id:
        type: integer
      newPWD:
        type: string
    type: object
  entities.AdminCreate:
    properties:
      password:
        type: string
      phone:
        type: integer
    type: object
  entities.AdminLogin:
    properties:
      password:
        type: string
      phone:
        type: integer
    type: object
  entities.BreadBase:
    properties:
      count:
        type: integer
      description:
        type: string
      name:
        type: string
      photo:
        type: string
      price:
        type: number
    type: object
  entities.UserChangeName:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  entities.UserChangePassword:
    properties:
      id:
        type: integer
      password:
        type: string
    type: object
  entities.UserCreate:
    properties:
      name:
        type: string
      password:
        type: string
      phone:
        type: integer
    type: object
  entities.UserLogin:
    properties:
      password:
        type: string
      phone:
        type: integer
    type: object
info:
  contact: {}
paths:
  /admin/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: AdminID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get user, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get admin
      tags:
      - public
  /admin/change:
    put:
      consumes:
      - application/json
      parameters:
      - description: admin change pwd
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.AdminChangePWD'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change pwd, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ChangePWD admin
      tags:
      - public
  /admin/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: admin create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.AdminCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create admin
      tags:
      - public
  /admin/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: AdminID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully delite user, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delite admin
      tags:
      - public
  /admin/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: admin login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.AdminLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login user, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login admin
      tags:
      - public
  /bread/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: BreadID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get bread, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get bread
      tags:
      - public
  /bread/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: bread create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.BreadBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created bread, returning JWT and Session
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create bread
      tags:
      - public
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get user
          schema:
            type: integer
        "400":
          description: Invalid UserID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user
      tags:
      - user
  /user/change/name:
    put:
      consumes:
      - application/json
      parameters:
      - description: change name
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.UserChangeName'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: integer
        "400":
          description: Invalid id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change username
      tags:
      - user
  /user/change/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: change name
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.UserChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: integer
        "400":
          description: Invalid id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change password
      tags:
      - user
  /user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: user create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /user/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted
          schema:
            type: integer
        "400":
          description: Invalid id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login user
          schema:
            type: integer
        "400":
          description: Invalid password
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
swagger: "2.0"
